### ISSUE TITLE
Fresh server, everything updated, throws this error when adding esx_shops

### ISSUE THREAD

**Issue by BrickTree** [ESX-Org/esx_shops#32] opened 2018-11-06 08:04 UTC
Error resuming coroutine: server/main.lua:27: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:27: in local 'cb'
        @mysql-async/lib/MySQL.lua:204: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>

EDIT: This is fixed by adding bread and water to the items table in the database.

**Comment by ElPumpo** [comment] 2018-11-19 17:40
Duplicate of #29

**Closed by ElPumpo** 2018-11-19 17:40 UTC
